version: '3.8'

services:
  db:
    image: 'postgres:13.6'
    restart: unless-stopped
    tty: true
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/db-data:/var/lib/postgresql/data
networks:
  default:
    name: todo-network
