version: '3.8'

services:
  main:
    build: .
    env_file:
        - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/todo-api
    command: air main.go -b 0.0.0.0
networks:
  default:
    name: todo-network
